version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - lancedb
    env_file:
      - .env

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: redis_cache
  
  lancedb:
    build:
      context: .
      dockerfile: Dockerfile.lancedb
    container_name: lancedb
    ports:
      - "8080:8080"
    volumes:
      - lancedb_data:/data

  daft_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: daft_worker
    command: tail -f /dev/null 
    volumes:
      - .:/usr/src/app
    depends_on:
      - lancedb
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  lancedb_data: